problems/urls.py
from django.urls import path

from . import views

app_name = "problems"
urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new_problem, name="new"),
    path("search/", views.search, name="search"),
    path("<int:problem_id>/", views.detail, name="detail"),
    path("<int:problem_id>/edit/", views.edit_problem, name="edit"),
]

prog_eng_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("problems/", include("problems.urls")),
    path("quizzes/", include("quizzes.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include(("django.contrib.auth.urls", "accounts"))),
]

quizzes/urls.py
from django.urls import path

from . import views

app_name = "quizzes"
urlpatterns = [
    path("", views.index, name="index"),
    path("user/<username>/", views.index, name="index"),
    path("new/", views.new_quiz, name="new"),
    path("<int:quiz_id>/", views.detail, name="detail"),
    path("<int:quiz_id>/delete/", views.delete_quiz, name="delete"),
    path("<int:quiz_id>/rename", views.rename_quiz, name="rename"),
    path(
        "<int:quiz_id>/<int:var_index>/modify/<int:entry_index>",
        views.modify_quiz_entry,
        name="modify-entry",
    ),
    path("<int:quiz_id>/add-variant", views.add_quiz_variant, name="add-variant",),
    path(
        "<int:quiz_id>/<int:var_index>/modify",
        views.modify_quiz_variant,
        name="modify-variant",
    ),
]

quizzes/models.py
from django.db import models
from django.contrib.auth.models import User


def get_default_user():
    default_user = User.objects.filter(username="ksidorov").first()
    assert default_user is not None
    return default_user.pk


class Quiz(models.Model):
    pub_date = models.DateTimeField(auto_now=True)
    title = models.CharField(default="Новая контрольная", max_length=32)
    editor = models.ForeignKey(User, on_delete=models.CASCADE, default=get_default_user)

    @property
    def variant_ids(self):
        return self.get_quizvariant_order()

    @property
    def variants(self):
        return QuizVariant.objects.filter(pk__in=self.get_quizvariant_order())


class QuizVariant(models.Model):
    quiz = models.ForeignKey(Quiz, null=False, on_delete=models.CASCADE)

    @property
    def entry_ids(self):
        return self.get_quizentry_order()

    @property
    def entries(self):
        return QuizEntry.objects.filter(pk__in=self.get_quizentry_order())

    class Meta:
        order_with_respect_to = "quiz"

    def save(self, *args, **kwargs):
        instance = super(QuizVariant, self).save(*args, **kwargs)
        self.quiz.save()
        return instance


class QuizEntry(models.Model):
    quiz_var = models.ForeignKey(QuizVariant, null=False, on_delete=models.CASCADE)
    problem = models.ForeignKey(
        "problems.Problem", null=False, on_delete=models.CASCADE
    )

    class Meta:
        order_with_respect_to = "quiz_var"

    def save(self, *args, **kwargs):
        instance = super(QuizEntry, self).save(*args, **kwargs)
        self.quiz_var.save()
        return instance

quizzes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.models import User
from django.apps import apps

from .models import QuizEntry, Quiz, QuizVariant


def index(request, username=None):
    quizzes = Quiz.objects
    user = None
    if username is not None:
        user = get_object_or_404(User, username=username)
        quizzes = quizzes.filter(editor=user)
    quizzes = quizzes.order_by("-pub_date")
    return render(request, "quizzes/index.html", {"quizzes": quizzes, "editor": user})


@require_POST
def new_quiz(request):
    quiz = Quiz()
    quiz.save()
    return HttpResponseRedirect(reverse("quizzes:detail", args=(quiz.id,)))


def detail(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    return render(request, "quizzes/detail.html", {"quiz": quiz})


def delete_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    quiz.delete()
    return HttpResponseRedirect(reverse("quizzes:index"))


@require_POST
def rename_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    new_title = request.POST["title"]
    quiz.title = new_title
    quiz.save()
    return HttpResponse(status=200)


@require_POST
def modify_quiz_entry(request, quiz_id, var_index, entry_index):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    quiz_var = quiz.variants[var_index - 1]
    order = list(quiz_var.entry_ids)
    if "up" in request.POST:
        order[entry_index - 2], order[entry_index - 1] = (
            order[entry_index - 1],
            order[entry_index - 2],
        )
        quiz_var.set_quizentry_order(order)
    elif "down" in request.POST:
        order[entry_index - 1], order[entry_index] = (
            order[entry_index],
            order[entry_index - 1],
        )
        quiz_var.set_quizentry_order(order)
    elif "remove" in request.POST:
        quiz_var.entries[entry_index - 1].delete()
    return HttpResponseRedirect(reverse("quizzes:detail", args=(quiz_id,)))


@require_POST
def add_quiz_variant(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    quiz_var = QuizVariant(quiz=quiz)
    quiz_var.save()
    return HttpResponseRedirect(reverse("quizzes:detail", args=(quiz_id,)))


@require_POST
def modify_quiz_variant(request, quiz_id, var_index):
    Problem = apps.get_model("problems", "Problem")
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    quiz_var = quiz.variants[var_index - 1]
    if "insert" in request.POST:
        problem_id = request.POST.get("problem", None)
        problem = Problem.objects.get(pk=problem_id)
        if QuizEntry.objects.filter(quiz_var=quiz_var, problem=problem).count() == 0:
            quiz_entry = QuizEntry(quiz_var=quiz_var, problem=problem)
            quiz_entry.save()
    elif "remove" in request.POST:
        quiz_var.delete()
    return HttpResponseRedirect(reverse("quizzes:detail", args=(quiz_id,)))

quizzes/templates/quizzes/detail.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'quizzes/detail.js' %}"></script>
{% endblock %}

{% block content %}

<form action="{% url 'quizzes:add-variant' quiz.id %}" method="post">
    {% csrf_token %}
    <h1>
        Контрольная работа
        {% if user == quiz.editor %}
        "<span id="quiz-title">{{ quiz.title }}</span><input type="text" style="display: none;" id="quiz-title-editor"
            value="{{ quiz.title }}">"<button type="button" class="btn btn-outline-secondary quiz-edit-control"
            data-href="{% url 'quizzes:rename' quiz.id %}" id="rename-btn">
            <i class="fas fa-edit"></i>
        </button>
        {% else %}
        {{ quiz.title }}
        {% endif %}
    </h1>

    {% if user == quiz.editor %}

    <button style="display: inline;" class="quiz-edit-control btn btn-outline-success quiz-newtask-toggle"
        data-index="{{ forloop.counter }}">
        <i class="fas fa-file"></i> Добавить вариант
    </button>
    {% endif %}

</form>

<div class="btn-group-toggle" data-toggle="buttons">
    {% if user == quiz.editor %}
    <label class="btn btn-outline-primary">
        <input type="checkbox" autocomplete="off" id="read-only-toggle">Только чтение
    </label>
    {% endif %}

    <button class="btn btn-success" onClick="window.print()">
        <i class="fas fa-print"></i> Печать
    </button>
</div>

<p>
    <small class="text-muted">Обновлено: {{ quiz.pub_date }}</small>
    <br>
    <small class="text-muted">Редактор: {{ quiz.editor.username }}</small>
</p>

{% for var in quiz.variants %}

<form action="{% url 'quizzes:modify-variant' quiz.id forloop.counter %}" method="post">
    {% csrf_token %}
    <h2>
        Вариант №{{ forloop.counter }}
        {% if user == quiz.editor %}

        <button type="button" style="display: inline;"
            class="quiz-edit-control btn btn-outline-success quiz-newtask-toggle" data-index="{{ forloop.counter }}">
            <i class="fas fa-file"></i> Добавить новую задачу
        </button>
        <button name="remove" style="display: inline;"
            class="quiz-edit-control btn btn-outline-danger quiz-newtask-toggle"">
            <i class=" fas fa-trash"></i> Удалить вариант
        </button>

        {% endif %}
    </h2>
</form>

{% for entry in var.entries %}

<form action="{% url 'quizzes:modify-entry' quiz.id forloop.parentloop.counter forloop.counter %}" method="post">
    {% csrf_token %}

    <p>
        <mark>
            <a class="problem-link"
                href="{% url 'problems:detail' entry.problem.id %}">№{{ forloop.counter }}</a></mark>

        {% if user == quiz.editor %}

        {% if not forloop.first %}
        <button style="display: inline;" type="submit" name="up" class="quiz-edit-control btn btn-outline-primary"
            value="Up">
            <i class="fas fa-angle-double-up"></i>
        </button>
        {% endif %}

        {% if not forloop.last %}
        <button style="display: inline;" type="submit" name="down" class="quiz-edit-control btn btn-outline-primary"
            value="Down">
            <i class="fas fa-angle-double-down"></i>
        </button>
        {% endif %}

        <button style="display: inline;" type="submit" name="remove" class="quiz-edit-control btn btn-outline-danger"
            value="Delete">
            <i class="fas fa-trash"></i>
        </button>

        {% endif %}

        {{ entry.problem.question_text }}
    </p>
</form>

{% endfor %}

{% if user == quiz.editor %}

<div style="display: none;" data-href="{% url 'quizzes:modify-variant' quiz.id forloop.counter %}"
    class="quiz-problem-selector" id="problem-selector-{{ forloop.counter }}">

    <div class="form-inline">
        <input type="text" class="form-control" name="q" placeholder="Введите запрос..">
        <button class="btn btn-primary" data-href="{% url 'problems:search' %}">Искать</button>
    </div>
    <div id="problem-selector-{{ forloop.counter }}-candidates">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>

            <tbody>

            </tbody>
        </table>
    </div>
</div>

{% endif %}

{% endfor %}

<div class="pagebreak"> </div>

<h2>Ответы</h2>

{% for var in quiz.variants %}

<h3>Вариант №{{ forloop.counter }}</h3>

{% for entry in var.entries %}

<p>
    <mark>№{{ forloop.counter }}</mark>

    {{ entry.problem.answer_text }}
</p>

{% endfor %}

{% endfor %}

{% endblock %}

quizzes/templates/quizzes/index.html
{% extends "base.html" %}

{% block content %}

<h1>Контрольные работы {% if editor %} (от пользователя {{ editor.username }}) {% endif %}</h1>

{% if quizzes %}

<table class="table table-hover">
    <form action="{% url 'quizzes:new' %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Новая контрольная" />
    </form>

    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Название</th>
            <th scope="col">Количество вариантов</th>
            <th scope="col"></th>
            <th scope="col">Последнее изменение</th>
        </tr>
    </thead>
    <tbody>
        {% for quiz in quizzes %}

        <tr>
            <th scope=" row">{{ quiz.id }}</th>
            <td>{{ quiz.title }}</td>
            <td>{{ quiz.variant_ids|length }}</td>
            <td>
                <form class="form-inline" action="{% url 'quizzes:delete' quiz.id %}" method="post">
                    {% csrf_token %}
                    <a class="btn btn-primary" href="{% url 'quizzes:detail' quiz.id %}">
                        <i class="fas fa-eye"></i> <span>Подробнее...</span>
                    </a>

                    {% if user == quiz.editor %}
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash"></i> <span>Удалить</span>
                    </button>
                    {% endif %}
                </form>
            </td>
            <td>{{ quiz.pub_date }}</td>
        </tr>

        {% endfor %}
    </tbody>
</table>

{% else %}
<form action="{% url 'quizzes:new' %}" method="post">
    {% csrf_token %}
    <p>Здесь пока пусто — не желаете <input type="submit" class="btn btn-primary" value="добавить" /> новую
        контрольную
        работу?</p>

</form>
{% endif %}

{% endblock %}