problems/urls.py
from django.urls import path

from . import views

app_name = "problems"
urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new_problem, name="new"),
    path("search/", views.search, name="search"),
    path("<int:problem_id>/", views.detail, name="detail"),
    path("<int:problem_id>/edit/", views.edit_problem, name="edit"),
]

prog_eng_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("problems/", include("problems.urls")),
    path("quizzes/", include("quizzes.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include(("django.contrib.auth.urls", "accounts"))),
]

quizzes/urls.py
from django.urls import path

from . import views

app_name = "quizzes"
urlpatterns = [
    path("", views.index, name="index"),
    path("user/<username>/", views.index, name="index"),
    path("new/", views.new_quiz, name="new"),
    path("<int:quiz_id>/", views.detail, name="detail"),
    path("<int:quiz_id>/delete/", views.delete_quiz, name="delete"),
    path("<int:quiz_id>/rename", views.rename_quiz, name="rename"),
    path(
        "<int:quiz_id>/<int:var_index>/modify/<int:entry_index>",
        views.modify_quiz_entry,
        name="modify-entry",
    ),
    path("<int:quiz_id>/add-variant", views.add_quiz_variant, name="add-variant",),
    path(
        "<int:quiz_id>/<int:var_index>/modify",
        views.modify_quiz_variant,
        name="modify-variant",
    ),
]

problems/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    tag_name = models.CharField(max_length=32)

    def __str__(self):
        return self.tag_name


def get_default_user():
    default_user = User.objects.filter(username="ksidorov").first()
    assert default_user is not None
    return default_user.pk


class Problem(models.Model):
    question_text = models.TextField()
    answer_text = models.TextField()
    submitter = models.ForeignKey(
        User, on_delete=models.CASCADE, default=get_default_user
    )
    pub_date = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag)

    @property
    def tag_string(self):
        return ", ".join((str(x) for x in self.tags.all()))

problems/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.urls import reverse
from django.views.decorators.http import require_http_methods, require_GET
from django.contrib.auth.decorators import login_required

from .models import Problem, Tag

import re


def index(request):
    problems = Problem.objects
    try:
        tag = Tag.objects.get(tag_name=request.GET.get("tag", None))
        problems = problems.filter(tags=tag)
    except Tag.DoesNotExist:
        tag = None
    problems = problems.order_by("-pub_date")
    return render(request, "problems/index.html", {"problems": problems, "tag": tag})


def extract_tags(tag_string):
    tag_strings = [x.strip().lower() for x in tag_string.split(",") if x.strip() != ""]
    return [
        Tag.objects.get_or_create(tag_name=tag_string)[0] for tag_string in tag_strings
    ]


@login_required
def edit_problem(request, problem_id):
    problem = Problem.objects.filter(pk=problem_id).first()
    if problem is None:
        return redirect(reverse("problems:new"))
    if request.user != problem.submitter:
        return HttpResponseRedirect(reverse('problems:index'))
    if request.method == "POST":
        question = request.POST.get("question", "")
        answer = request.POST.get("answer", "")

        if question != "" and answer != "":
            problem.question_text = question
            problem.answer_text = answer
            problem.save()
            problem.tags.set(extract_tags(request.POST.get("tags", "")))
            return HttpResponseRedirect(reverse("problems:detail", args=(problem_id,)))
        else:
            if question == "":
                error_msg = "Пожалуйста, запишите условие задачи."
            else:
                error_msg = "Пожалуйста, укажите ответ."
            return render(
                request,
                "problems/editor.html",
                {
                    "question_text": question,
                    "answer_text": answer,
                    "error_message": error_msg,
                },
            )

    if request.method == "GET":
        return render(request, "problems/editor.html", {"target_problem": problem})


@login_required
def new_problem(request):
    if request.method == "POST":
        question = request.POST.get("question", "")
        answer = request.POST.get("answer", "")
        if question != "" and answer != "":
            new_problem = Problem(question_text=question, answer_text=answer, submitter=request.user)
            new_problem.save()
            new_problem.tags.set(extract_tags(request.POST.get("tags", "")))
            return HttpResponseRedirect(
                reverse("problems:detail", args=(new_problem.id,))
            )
        else:
            if question == "":
                error_msg = "Пожалуйста, запишите условие задачи."
            else:
                error_msg = "Пожалуйста, укажите ответ."
            return render(
                request,
                "problems/editor.html",
                {
                    "question_text": question,
                    "answer_text": answer,
                    "error_message": error_msg,
                },
            )

    if request.method == "GET":
        return render(request, "problems/editor.html")


def detail(request, problem_id):
    problem = get_object_or_404(Problem, pk=problem_id)

    return render(request, "problems/detail.html", {"problem": problem})


@require_GET
def search(request):
    search_string = request.GET.get("q", "")
    tags = []
    matches = list(re.finditer(r"tag:(?P<tag>\w+)\s?", search_string))
    for m in matches:
        tag = Tag.objects.filter(tag_name=m.group("tag")).first()
        if tag is not None:
            tags.append(tag)
        search_string = search_string.replace(m.group(), "")
    res = Problem.objects.filter(question_text__icontains=search_string)
    for tag in tags:
        res = res.filter(tags=tag)
    return JsonResponse(
        {
            "status": "ok",
            "problems": [{"id": x.pk, "text": x.question_text} for x in res],
        }
    )

problems/templates/problems/detail.html
{% extends "base.html" %}

{% block content %}

<h1>Задача №{{ problem.id }}</h1>

<p>
    <small class="text-muted">Обновлено: {{ problem.pub_date }}</small><br>
    <small class="text-muted">Отправитель:
        {{ problem.submitter.username }}</small></p>

<h2>Условие задачи</h2>

<p> {{ problem.question_text }} </p>

<h2>Ответ</h2>

<p> {{ problem.answer_text }} </p>

<h2>Метки</h2>

<div style="margin-bottom: 10px">
    {% with tags=problem.tags.all %}
    {% for tag in tags %}
    <a href="{% url 'problems:index' %}?tag={{tag}}" class="badge badge-primary">
        {{ tag }}
    </a>
    {% endfor %}
    {% endwith %}
</div s>

<a class="btn btn-warning" href="{% url 'problems:edit' problem.id %}">
    <i class="fas fa-edit"></i> <span>Редактировать</span>
</a>

{% endblock %}

problems/templates/problems/editor.html
{% extends "base.html" %}

{% block content %}

{% if target_problem %}
{% url 'problems:edit' target_problem.id as target_url %}
{% else %}
{% url 'problems:new' as target_url %}
{% endif %}


<h1>
    {% if target_problem %}
    Задача №{{ target_problem.id }}
    {% else %}
    Новая задача
    {% endif %}
</h1>


<form action="{{ target_url }}" method="post">
    {% csrf_token %}

    {% if error_message %}
    <div class="alert alert-danger" role="alert">
        {{ error_message }}
    </div>
    {% endif %}

    <div class="form-group">
        <label for="question-input">Текст вопроса</label>
        <textarea class="form-control" name="question" id="question-input" placeholder="Введите текст вопроса"
            rows=3>{% firstof question_text target_problem.question_text %}</textarea>

        <small class="form-text text-muted">
            Вы также можете вводить LaTeX-разметку — например,
            <code>\( \vec{F} = m\vec{a} \)</code> отобразится как \( \vec{F} = m\vec{a}\).</small>
    </div>

    <div class="form-group">
        <label for="answer-input">Текст ответа</label>
        <textarea class="form-control" name="answer" id="answer-input" placeholder="Введите текст ответа"
            rows=1>{% firstof answer_text target_problem.answer_text %}</textarea>
    </div>

    <div class="form-group">
        <label for="tag-input">Метки</label>
        <input type="text" class="form-control" name="tags" id="tag-input" placeholder="Введите метки задачи"
            value="{% firstof tag_string target_problem.tag_string %}"></input>
        <small class="form-text text-muted">Введите метки задачи через запятую</small>
    </div>

    <input class="btn btn-primary" type="submit" value="Записать">
</form>

{% endblock %}

problems/templates/problems/index.html
{% extends "base.html" %}

{% block content %}

<h1>Банк задач {% if tag %}(метка "{{ tag }}"){% endif %}</h1>

{% if problems %}


<a class="btn btn-primary" href="{% url 'problems:new' %}">Новая задача</a>

<table class="table table-hover">

    <thead>
        <tr>
            <th scope="col">№</th>
            <th scope="col">Текст задачи</th>
            <th scope="col"></th>
            <th scope="col">Последнее изменение</th>
        </tr>
    </thead>
    <tbody>
        {% for problem in problems %}

        <!--  class="clickable-row" data-href="{% url 'problems:detail' problem.id %}" -->
        <tr>
            <th scope="row">{{ problem.id }}</th>
            <td>{{ problem.question_text }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'problems:detail' problem.id %}">
                    <i class="fas fa-eye"></i> <span>Подробнее...</span>
                </a>
                {% if user == problem.submitter %}
                <a class="btn btn-warning" href="{% url 'problems:edit' problem.id %}">
                    <i class="fas fa-edit"></i> <span>Редактировать</span>
                </a>
                {% endif %}
            </td>
            <td>{{ problem.pub_date }}</td>
        </tr>

        {% endfor %}
    </tbody>
</table>

{% else %}
<p>Здесь пока пусто — не желаете добавить новую задачу?</p>
{% endif %}

{% endblock %}