problems/urls.py
from django.urls import path

from . import views

app_name = "problems"
urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new_problem, name="new"),
    path("search/", views.search, name="search"),
    path("<int:problem_id>/", views.detail, name="detail"),
    path("<int:problem_id>/edit/", views.edit_problem, name="edit"),
]

prog_eng_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("problems/", include("problems.urls")),
    path("quizzes/", include("quizzes.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include(("django.contrib.auth.urls", "accounts"))),
]

quizzes/urls.py
from django.urls import path

from . import views

app_name = "quizzes"
urlpatterns = [
    path("", views.index, name="index"),
    path("user/<username>/", views.index, name="index"),
    path("new/", views.new_quiz, name="new"),
    path("<int:quiz_id>/", views.detail, name="detail"),
    path("<int:quiz_id>/delete/", views.delete_quiz, name="delete"),
    path("<int:quiz_id>/rename", views.rename_quiz, name="rename"),
    path(
        "<int:quiz_id>/<int:var_index>/modify/<int:entry_index>",
        views.modify_quiz_entry,
        name="modify-entry",
    ),
    path("<int:quiz_id>/add-variant", views.add_quiz_variant, name="add-variant",),
    path(
        "<int:quiz_id>/<int:var_index>/modify",
        views.modify_quiz_variant,
        name="modify-variant",
    ),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>Проект</title>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />

    {% block scripts %}
    {% endblock scripts %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Демо</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'problems:index' %}">Банк задач</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'quizzes:index' %}">Контрольные работы</a>
                </li>

            </ul>

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Вы вошли как {{user.get_username}}</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'quizzes:index' user.get_username %}">Мои контрольные</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
                </li>

                {% else %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Войти</a>
                </li>

                {% endif %}
            </ul>

        </div>


    </nav>

    <main role="main" class="container">
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>